#!/usr/bin/env python3


import boto3
from botocore.exceptions import ClientError

# Initialize a Boto3 DynamoDB client
dynamodb = boto3.client('dynamodb', endpoint_url='https://dynamodb.us-east-1.amazonaws.com')

# Specify the table name
table_name = 'CrdDdb-DynamoDBTable-1XP2RIF6G70MT'

try:
    # Attempt to describe the table
    response = dynamodb.describe_table(TableName=table_name)
    print(f"Table '{table_name}' exists.")
    # Additional code to process the response if needed
except ClientError as e:
    if e.response['Error']['Code'] == 'ResourceNotFoundException':
        print(f"Table '{table_name}' does not exist.")
    else:
        # Handle other possible exceptions
        print("An error occurred:", e)